### ISSUE TITLE
Set a last_seen_at time to allow new users to get digests

### ISSUE THREAD

**Issue by YesThatAllen** [watchmanmonitoring/discourse_user_importer#1]
Per this topic, users who don't login after being added won't get digests

https://meta.discourse.org/t/are-digest-emails-sent-to-people-who-have-no-last-seen-date/25146/18

could be added in the script or trigger..

**Comment by therealx** [comment]
Closed via defaults https://github.com/watchmanmonitoring/discourse_user_importer/wiki/Column-Defaults:-Sets-a-value-few-new-records
